title: "Hong Kong Compiler Engineering Group"
email: raventid@hk_compilers.org
url: "https://hong-kong-compeng.github.io"
# Remove the following line if you are serving your website at your
# github.io home page rather than at a sub-page (in my case
# https://raxod502.github.io/example-website).
baseurl: "/web"
description: "A community for anyone passionate about compiler development using OCaml."
navbar:
  - title: About
    path: /about
  - title: Roadmap
    path: /example/
  # - title: Subpage
  #   path: /example/subpage
theme: minima
markdown: kramdown
defaults:
  - scope:
      path: ""
    values:
      layout: page
