title: My Compiler Organization
description: A community for compiler enthusiasts and functional programming lovers.
theme: minima
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Optional settings
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "http://example.com" # the base hostname & protocol for your site
# author: "Your Name" # author name
# email: "your-email@example.com" # author email
# twitter_username: "your_twitter" # Twitter username
# github_username: "your_github" # GitHub username
# google_analytics: "UA-XXXXXXXX-X" # Google Analytics tracking ID

# Uncomment to enable pagination
# paginate: 5
# paginate_path: "/page:num/"